### ISSUE TITLE
Could you stop sending an e-mail to me? 

### ISSUE THREAD

**Issue by nzw0301** [chalice-dev/awesome-chalice#6]
From #5

@brianmingus2  I would like to ask you to remove my e-mail address from such a list. I'm afraid that I have never ever starred this repo as well because I didn't know this repo before I had received the email.

**Comment by brianmingus2** [comment]
I would be unable to remove your email from being publicly listed on your GitHub profile page. You could modify your preferences, or let people know when it would be appropriate on your contact page. If I were you, I’d remove it completely while you finish your PhD dissertation.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Kento Nozawa ***@***.***>
Sent: Friday, August 6, 2021 12:41:23 PM
To: chalice-dev/awesome-chalice ***@***.***>
Cc: Brian Mingus ***@***.***>; Mention ***@***.***>
Subject: [chalice-dev/awesome-chalice] Could you stop sending an e-mail to me? (#6)


From #5<https://github.com/chalice-dev/awesome-chalice/issues/5>

@brianmingus2<https://github.com/brianmingus2> I would like to ask you the remove my e-mail address from such a list. I'm afraid that I have never ever started this repo as well because I didn't know this repo before I received the email.

**Comment by nzw0301** [comment]
I know I can remove my e-mail from my github profile, but I don't want to do so because I also receive important e-mails from other github users who see my github profile.

> I got your e-mail from the list of people who had starred aws/chalice on GitHub :)
I mean the list you have.

**Comment by brianmingus2** [comment]
I don’t have any such list, apologies.  Such a list is maintained by both you and GitHub.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nzw0301** [comment]
At least, I don't have a "list". My request is still the same: please do not send an e-mail about this repo that is not related to me at all anymore.

I appreciate your understanding in advance.

**Comment by brianmingus2** [comment]
Unfortunately I will not be able to remove your publicly listed e-mail address from your GitHub profile page. Only you can do that.
